# Generated by Django 3.1.1 on 2020-09-12 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('credit', 'credit')], default='deposit', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='contract_begin_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='contract_create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='contract_end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='money',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='settlement_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.currency'),
        ),
    ]
