# Generated by Django 3.1.1 on 2020-09-12 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'rub'), ('USD', 'usd')], max_length=15)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.bank')),
            ],
        ),
    ]
