# Generated by Django 3.1.1 on 2020-09-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200912_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='name',
            field=models.CharField(default='', max_length=127),
        ),
    ]
