# Generated by Django 3.1.1 on 2020-09-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_account_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='course',
            field=models.FloatField(null=True),
        ),
    ]
