# Generated by Django 3.1.1 on 2020-09-13 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200913_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='reports.company'),
        ),
    ]
