# Generated by Django 3.1.1 on 2020-09-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20200913_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='company_types',
            new_name='company_type',
        ),
    ]
