# Generated by Django 3.1.1 on 2020-09-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20200913_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='money',
            new_name='balance',
        ),
    ]
