# Generated by Django 3.1.1 on 2020-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_account_summ'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
