# Generated by Django 3.1.1 on 2020-09-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_account_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('Депозит', 'Депозит'), ('Кредит', 'Кредит')], default='Депозит', max_length=15),
        ),
    ]
