# Generated by Django 3.1.1 on 2020-09-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20200913_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
